'use client';
import React, { useEffect, useState } from 'react';
import { Search, Plus, RefreshCw, Users, MessageSquareWarning, Gift, X, Check } from 'lucide-react';
import { crmApi, Customer, Complaint, ComplaintSeverity, ComplaintStatus } from '@/api/crm';
import { Button, StatCard } from '@/components/ui';

const input='w-full rounded-xl border border-black/10 bg-white px-3 py-2.5 text-xs outline-none focus:border-[#C79A3B]';

export default function CRMWorkspace(){
 const [tab,setTab]=useState<'customers'|'complaints'>('customers'); const [customers,setCustomers]=useState<Customer[]>([]); const [complaints,setComplaints]=useState<Complaint[]>([]); const [stats,setStats]=useState<Record<string,number>>({}); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Customer|null>(null); const [showNew,setShowNew]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{if(tab==='customers')setCustomers(await crmApi.customers(q));else{const [c,s]=await Promise.all([crmApi.complaints(),crmApi.complaintStats()]);setComplaints(c);setStats(s)}}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Unable to load CRM data')}finally{setLoading(false)}};
 useEffect(()=>{load()},[tab]);
 return <div className="space-y-4">
  <div><p className="text-[10px] font-bold uppercase tracking-wider text-[#B8862D]">Customer & Support</p><h1 className="text-2xl font-bold mt-1">CRM Center</h1><p className="text-xs text-[#707070] mt-1">Customers, order history, loyalty and complaints.</p></div>
  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><StatCard title="Customers" value={customers.length} icon={<Users className="w-4 h-4"/>}/><StatCard title="Open" value={stats.open||0} icon={<MessageSquareWarning className="w-4 h-4"/>}/><StatCard title="In Progress" value={stats.in_progress||0} icon={<RefreshCw className="w-4 h-4"/>}/><StatCard title="Resolved" value={stats.resolved||0} icon={<Check className="w-4 h-4"/>}/></div>
  <div className="flex gap-2"><button onClick={()=>setTab('customers')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='customers'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border border-black/10'}`}>Customers</button><button onClick={()=>setTab('complaints')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='complaints'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border border-black/10'}`}>Complaints</button><button onClick={load} className="ml-auto p-2 rounded-xl bg-white border border-black/10"><RefreshCw className="w-4 h-4"/></button></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs">{error}</div>}
  {tab==='customers'?<Customers customers={customers} q={q} setQ={setQ} onSearch={load} onSelect={setSelected} onNew={()=>setShowNew(true)} loading={loading}/>:<Complaints complaints={complaints} loading={loading} onRefresh={load}/>} 
  {selected&&<CustomerDetail customer={selected} onClose={()=>setSelected(null)} onUpdated={(c: any)=>{setSelected(c);load()}}/>}
  {showNew&&<NewCustomer onClose={()=>setShowNew(false)} onCreated={()=>{setShowNew(false);load()}}/>}
 </div>
}
function Customers({customers,q,setQ,onSearch,onSelect,onNew,loading}:any){return <div className="space-y-3"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-[#999]"/><input className={input+' pl-9'} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSearch()} placeholder="Search name, phone, email"/></div><Button onClick={onNew}><Plus className="w-4 h-4 mr-1"/>Customer</Button></div>{loading?<p className="text-xs text-[#777]">Loading...</p>:customers.map((c:Customer)=><button key={c.id} onClick={()=>onSelect(c)} className="w-full text-left p-3 rounded-2xl bg-white border border-black/5 shadow-sm"><div className="flex justify-between"><div><b className="text-sm">{c.name}</b><p className="text-[10px] text-[#777]">{c.phone} · {c.customer_type}</p></div><div className="text-right"><b className="text-sm">₹{Number(c.total_spent||0).toFixed(2)}</b><p className="text-[10px] text-[#777]">{c.total_orders} orders · {c.loyalty_points} pts</p></div></div></button>)}</div>}
function CustomerDetail({customer,onClose,onUpdated}:any){const [orders,setOrders]=useState<any[]>([]);const [points,setPoints]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{crmApi.orders(customer.id).then(setOrders).catch(()=>setOrders([]))},[customer.id]);const loyalty=async()=>{const n=Number(points);if(!Number.isInteger(n)||n===0)return;setBusy(true);try{onUpdated(await crmApi.loyalty(customer.id,n,'CRM adjustment'));setPoints('')}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 bg-black/30 p-3 flex items-end sm:items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-xl max-h-[90vh] overflow-y-auto p-4"><div className="flex justify-between"><div><h2 className="font-bold">{customer.name}</h2><p className="text-xs text-[#777]">{customer.phone} · {customer.email||'No email'}</p></div><button onClick={onClose}><X/></button></div><div className="grid grid-cols-3 gap-2 my-4"><StatCard title="Orders" value={customer.total_orders} icon={<Users className="w-4 h-4"/>}/><StatCard title="Spent" value={`₹${Number(customer.total_spent||0).toFixed(0)}`} icon={<Gift className="w-4 h-4"/>}/><StatCard title="Points" value={customer.loyalty_points} icon={<Gift className="w-4 h-4"/>}/></div><div className="flex gap-2 mb-4"><input className={input} value={points} onChange={e=>setPoints(e.target.value)} type="number" placeholder="+ / - loyalty points"/><Button disabled={busy} onClick={loyalty}><Gift className="w-4 h-4 mr-1"/>Adjust</Button></div><h3 className="font-bold text-sm mb-2">Order History</h3>{orders.map(o=><div key={o.id} className="p-2.5 border-b border-black/5 text-xs flex justify-between"><span>#{o.orderNumber||o.order_number} · {o.source}</span><b>₹{Number(o.grandTotal||o.total_amount||0).toFixed(2)}</b></div>)}</div></div>}
function NewCustomer({onClose,onCreated}:any){const [form,setForm]=useState({name:'',phone:'',email:'',customer_type:'REGULAR',notes:''});const [busy,setBusy]=useState(false);const save=async()=>{if(!form.name||!form.phone)return;setBusy(true);try{await crmApi.createCustomer(form as any);onCreated()}catch(e:any){alert(e?.response?.data?.detail||'Unable to create customer')}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 bg-black/30 p-3 flex items-center justify-center"><div className="bg-white rounded-2xl w-full max-w-md p-4 space-y-2"><div className="flex justify-between"><b>New Customer</b><button onClick={onClose}><X/></button></div>{[['name','Name'],['phone','Phone'],['email','Email']].map(([k,l])=><input key={k} className={input} placeholder={l} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select className={input} value={form.customer_type} onChange={e=>setForm({...form,customer_type:e.target.value})}><option>REGULAR</option><option>VIP</option><option>CORPORATE</option></select><textarea className={input} placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><Button disabled={busy} onClick={save}>Save Customer</Button></div></div>}
function Complaints({complaints,loading,onRefresh}:any){const [form,setForm]=useState({category:'FOOD_QUALITY',severity:'MEDIUM',description:''});const save=async()=>{if(!form.description)return;try{await crmApi.createComplaint(form);setForm({...form,description:''});onRefresh()}catch(e:any){alert(e?.response?.data?.detail||'Unable to create complaint')}};return <div className="space-y-3"><div className="p-4 bg-white rounded-2xl border border-black/5"><h3 className="font-bold text-sm mb-2">Log Complaint</h3><div className="grid sm:grid-cols-2 gap-2"><input className={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category"/><select className={input} value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><textarea className={input+' sm:col-span-2'} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Complaint details"/><Button onClick={save}>Create Complaint</Button></div></div>{loading?<p className="text-xs">Loading...</p>:complaints.map((c:Complaint)=><div key={c.id} className="p-3 bg-white rounded-2xl border border-black/5"><div className="flex justify-between"><b className="text-xs">{c.complaint_number}</b><span className="text-[9px] px-2 py-1 rounded-full bg-[#F1E4C5]">{c.status}</span></div><p className="text-xs mt-2">{c.description}</p><p className="text-[10px] text-[#777] mt-1">{c.category} · {c.severity} · {new Date(c.created_at).toLocaleString()}</p></div>)}</div>}
