'use client';
import React,{useEffect,useState} from 'react';
import {WalletCards,RefreshCw,PlusCircle,CheckCircle2,Scale} from 'lucide-react';
import {financeControlApi} from '@/api/financeControl';
import {Button,StatCard,Modal} from '@/components/ui';
const input='w-full px-3 py-2 rounded-xl border border-black/10 bg-white text-xs outline-none focus:border-[#C79A3B]';
export default function FinanceControlWorkspace(){
 const [tab,setTab]=useState<'expenses'|'reconciliation'>('expenses'),[s,setS]=useState<any>(),[expenses,setExpenses]=useState<any[]>([]),[recs,setRecs]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const [a,b,c,d]=await Promise.all([financeControlApi.summary(),financeControlApi.expenses(),financeControlApi.reconciliations(),financeControlApi.accounts()]);setS(a);setExpenses(b);setRecs(c);setAccounts(d)}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Unable to load finance control')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const approve=async(id:string)=>{try{await financeControlApi.approveExpense(id);await load()}catch(e:any){setError(e?.response?.data?.detail||'Approval failed')}};
 const closeRec=async(id:string)=>{try{await financeControlApi.closeReconciliation(id);await load()}catch(e:any){setError(e?.response?.data?.detail||'Reconciliation failed')}};
 return <div className="space-y-4"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#B8862D]">Finance Operations</p><h1 className="text-2xl font-bold mt-1 flex items-center gap-2"><WalletCards className="w-6 h-6 text-[#B8862D]"/>Expense & Reconciliation</h1><p className="text-xs text-[#707070]">Control operating expenses and reconcile cash/bank balances.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={load} loading={busy}><RefreshCw className="w-3 h-3 mr-1"/>Sync</Button><Button size="sm" onClick={()=>setShow(true)}><PlusCircle className="w-3 h-3 mr-1"/>New {tab==='expenses'?'Expense':'Reconciliation'}</Button></div></div>
 {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><StatCard title="Expense Total" value={`₹${Number(s?.expenseTotal||0).toFixed(2)}`} icon={<WalletCards className="w-4 h-4"/>}/><StatCard title="Pending Approval" value={s?.pendingExpenses??0} icon={<CheckCircle2 className="w-4 h-4"/>}/><StatCard title="Open Reconciliations" value={s?.openReconciliations??0} icon={<Scale className="w-4 h-4"/>}/><StatCard title="Open Variance" value={`₹${Number(s?.openVariance||0).toFixed(2)}`} icon={<Scale className="w-4 h-4"/>}/></div>
 <div className="flex gap-2"><button onClick={()=>setTab('expenses')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='expenses'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border'}`}>Expenses</button><button onClick={()=>setTab('reconciliation')} className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='reconciliation'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border'}`}>Reconciliation</button></div>
 {tab==='expenses'?<div className="space-y-2">{expenses.length===0?<div className="p-6 bg-white rounded-2xl border text-xs text-[#707070]">No expenses recorded.</div>:expenses.map(x=><div key={x.id} className="p-4 bg-white rounded-2xl border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><b className="text-xs">{x.expenseNumber} · {x.category}</b><p className="text-xs mt-1">{x.description}</p><small>{x.paymentMethod} · {x.status}</small></div><div className="flex items-center gap-3"><b>₹{Number(x.amount).toFixed(2)}</b>{x.status==='PENDING'&&<Button size="sm" onClick={()=>approve(x.id)}>Approve</Button>}</div></div>)}</div>:<div className="space-y-2">{recs.length===0?<div className="p-6 bg-white rounded-2xl border text-xs text-[#707070]">No reconciliations recorded.</div>:recs.map(x=><div key={x.id} className="p-4 bg-white rounded-2xl border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><b className="text-xs">{x.reconciliationNumber}</b><p className="text-xs mt-1">Book ₹{Number(x.bookBalance).toFixed(2)} · Statement ₹{Number(x.statementBalance).toFixed(2)}</p><small>{x.status} · Variance ₹{Number(x.variance).toFixed(2)}</small></div>{x.status==='OPEN'&&<Button size="sm" onClick={()=>closeRec(x.id)}>Reconcile</Button>}</div>)}</div>}
 {show&&tab==='expenses'&&<ExpenseForm accounts={accounts} close={()=>setShow(false)} done={()=>{setShow(false);load()}}/>}{show&&tab==='reconciliation'&&<ReconForm accounts={accounts} close={()=>setShow(false)} done={()=>{setShow(false);load()}}/>}</div>}
function ExpenseForm({accounts,close,done}:{accounts:any[];close:()=>void;done:()=>void}){const [f,setF]=useState<any>({expense_date:new Date().toISOString(),category:'',description:'',amount:'',payment_method:'CASH',account_id:'',notes:''});const save=async()=>{try{await financeControlApi.createExpense({...f,amount:Number(f.amount)});done()}catch(e:any){alert(e?.response?.data?.detail||e?.message||'Could not create expense')}};return <Modal isOpen onClose={close} title="New Expense"><div className="space-y-3"><input className={input} placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><textarea className={input} placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input className={input} type="number" min="0.01" placeholder="Amount" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><select className={input} value={f.payment_method} onChange={e=>setF({...f,payment_method:e.target.value})}><option>CASH</option><option>BANK</option><option>UPI</option><option>CARD</option></select><select className={input} value={f.account_id} onChange={e=>setF({...f,account_id:e.target.value})}><option value="">Expense Account</option>{accounts.filter(a=>a.type==='EXPENSE').map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><div className="flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={save}>Submit</Button></div></div></Modal>}
function ReconForm({accounts,close,done}:{accounts:any[];close:()=>void;done:()=>void}){const [f,setF]=useState<any>({account_id:'',period_start:new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString(),period_end:new Date().toISOString(),statement_balance:''});const save=async()=>{try{await financeControlApi.createReconciliation({...f,statement_balance:Number(f.statement_balance)});done()}catch(e:any){alert(e?.response?.data?.detail||e?.message||'Could not create reconciliation')}};return <Modal isOpen onClose={close} title="New Reconciliation"><div className="space-y-3"><select className={input} value={f.account_id} onChange={e=>setF({...f,account_id:e.target.value})}><option value="">Cash / Bank Account</option>{accounts.filter(a=>['ASSET'].includes(a.type)).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input className={input} type="number" placeholder="Statement Balance" value={f.statement_balance} onChange={e=>setF({...f,statement_balance:e.target.value})}/><div className="flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={save}>Create</Button></div></div></Modal>}
