'use client';
import React from 'react';
import { hotelApi } from '@/api/hotel';
import { useOutlet } from '@/context/OutletContext';
import { BedDouble, CalendarCheck, ClipboardCheck, Plus, RefreshCw } from 'lucide-react';

const card=(label:string,value:any)=><div className="rounded-2xl border border-black/5 bg-white p-4 shadow-sm"><div className="text-[11px] uppercase tracking-wider text-[#707070]">{label}</div><div className="mt-1 text-2xl font-bold text-[#1C1C1C]">{value}</div></div>;
export default function HotelOperationsWorkspace(){
 const {activeOutlet}=useOutlet(); const [summary,setSummary]=React.useState<any>(); const [rooms,setRooms]=React.useState<any[]>([]); const [bookings,setBookings]=React.useState<any[]>([]); const [tasks,setTasks]=React.useState<any[]>([]); const [tab,setTab]=React.useState<'rooms'|'bookings'|'housekeeping'>('rooms'); const [loading,setLoading]=React.useState(true); const [error,setError]=React.useState('');
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const p=activeOutlet?.id?{branch_id:activeOutlet.id}:{};const [s,r,b,h]=await Promise.all([hotelApi.summary(activeOutlet?.id),hotelApi.rooms(p),hotelApi.bookings(p),hotelApi.housekeeping(p)]);setSummary(s);setRooms(r);setBookings(b);setTasks(h)}catch(e:any){setError(e?.response?.data?.error?.message||'Hotel operations unavailable.')}finally{setLoading(false)}},[activeOutlet?.id]);
 React.useEffect(()=>{load()},[load]);
 const setStatus=async(id:string,status:string)=>{await hotelApi.updateBooking(id,{status});load()}; const hkStatus=async(id:string,status:string)=>{await hotelApi.updateHousekeeping(id,{status});load()};
 return <div className="space-y-5">
  <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Hotel Operations</h1><p className="text-sm text-[#707070]">Rooms, reservations and housekeeping</p></div><button onClick={load} className="rounded-xl border px-3 py-2 bg-white"><RefreshCw className="w-4 h-4"/></button></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{card('Rooms',summary?.total_rooms??'—')}{card('Available',summary?.available_rooms??'—')}{card('Occupied',summary?.occupied_rooms??'—')}{card('Occupancy',summary?`${summary.occupancy_rate}%`:'—')}{card('Dirty',summary?.dirty_rooms??'—')}{card('Active Bookings',summary?.active_bookings??'—')}{card('Housekeeping',summary?.pending_housekeeping??'—')}{card('Out of Order',summary?.out_of_order_rooms??'—')}</div>
  <div className="flex gap-2 overflow-x-auto">{[['rooms','Rooms',BedDouble],['bookings','Bookings',CalendarCheck],['housekeeping','Housekeeping',ClipboardCheck]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold ${tab===id?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
  {loading?<div className="p-8 text-center text-[#707070]">Loading hotel operations…</div>:tab==='rooms'?<div className="grid grid-cols-2 md:grid-cols-4 gap-3">{rooms.map(r=><div key={r.id} className="rounded-2xl bg-white border p-4"><div className="flex justify-between"><b>Room {r.room_number}</b><span className="text-[10px] px-2 py-1 rounded-full bg-[#FAF8F5]">{r.status}</span></div><div className="text-sm text-[#707070] mt-2">{r.room_type} · {r.capacity} guests</div><div className="font-semibold mt-2">₹{Number(r.base_rate||0).toLocaleString()}</div></div>)}</div>:tab==='bookings'?<div className="space-y-2">{bookings.map(b=><div key={b.id} className="rounded-2xl bg-white border p-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><b>{b.booking_number}</b><div className="text-sm">{b.guest_name} · Room {b.room_number}</div><div className="text-xs text-[#707070]">{new Date(b.check_in).toLocaleString()} → {new Date(b.check_out).toLocaleString()}</div></div><div className="flex items-center gap-2"><span className="text-xs font-semibold">{b.status}</span>{b.status==='RESERVED'&&<button onClick={()=>setStatus(b.id,'CHECKED_IN')} className="px-3 py-2 rounded-lg bg-[#F1E4C5] text-[#B8862D] text-xs font-bold">Check in</button>}{b.status==='CHECKED_IN'&&<button onClick={()=>setStatus(b.id,'CHECKED_OUT')} className="px-3 py-2 rounded-lg bg-[#1C1C1C] text-white text-xs font-bold">Check out</button>}</div></div>)}</div>:<div className="space-y-2">{tasks.map(t=><div key={t.id} className="rounded-2xl bg-white border p-4 flex items-center justify-between gap-3"><div><b>Room {t.room_number}</b><div className="text-xs text-[#707070]">{t.task_type} · {new Date(t.scheduled_for).toLocaleString()}</div></div>{t.status==='PENDING'&&<button onClick={()=>hkStatus(t.id,'IN_PROGRESS')} className="px-3 py-2 rounded-lg bg-[#F1E4C5] text-[#B8862D] text-xs font-bold">Start</button>}{t.status==='IN_PROGRESS'&&<button onClick={()=>hkStatus(t.id,'COMPLETED')} className="px-3 py-2 rounded-lg bg-[#1C1C1C] text-white text-xs font-bold">Complete</button>}{t.status==='COMPLETED'&&<button onClick={()=>hkStatus(t.id,'INSPECTED')} className="px-3 py-2 rounded-lg bg-[#F1E4C5] text-[#B8862D] text-xs font-bold">Inspect</button>}<span className="text-xs">{t.status}</span></div>)}</div>}
 </div>
}
