import { useEffect, useState } from 'react';
import { MessageCircle, RefreshCw, Send, RotateCcw, Link2, Webhook, Unlink } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { notificationsApi, TelegramNotification, TelegramStatus, TelegramLink } from '@/api/notifications';

export default function TelegramNotificationWorkspace(){
 const [status,setStatus]=useState<TelegramStatus|null>(null),[chat,setChat]=useState(''),[message,setMessage]=useState(''),[title,setTitle]=useState(''),[rows,setRows]=useState<TelegramNotification[]>([]),[links,setLinks]=useState<TelegramLink[]>([]),[linkChat,setLinkChat]=useState(''),[linkUser,setLinkUser]=useState(''),[linkBranch,setLinkBranch]=useState(''),[webhookUrl,setWebhookUrl]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const load=async()=>{setError('');try{const [s,h,l]=await Promise.all([notificationsApi.status(),notificationsApi.history(),notificationsApi.links()]);setStatus(s);setRows(h);setLinks(l);}catch(e:any){setError(e?.response?.data?.detail||'Unable to load Telegram status/history.')}};
 useEffect(()=>{load()},[]);
 const send=async()=>{if(!chat.trim()||!message.trim())return;setLoading(true);setError('');try{await notificationsApi.queue({chat_id:chat.trim(),title:title.trim()||undefined,message:message.trim(),event_type:'MANUAL'});setMessage('');setTitle('');await load()}catch(e:any){setError(e?.response?.data?.detail||'Telegram send failed.')}finally{setLoading(false)}};
 const link=async()=>{if(!linkChat.trim()||!linkUser.trim())return;try{await notificationsApi.link({chat_id:linkChat.trim(),user_id:linkUser.trim(),branch_id:linkBranch.trim()||undefined});setLinkChat('');setLinkUser('');setLinkBranch('');await load()}catch(e:any){setError(e?.response?.data?.detail||'Telegram link failed.')}};
 const configure=async()=>{try{await notificationsApi.configureWebhook(webhookUrl.trim()||undefined);await load()}catch(e:any){setError(e?.response?.data?.detail||'Webhook configuration failed.')}};
 return <div className="space-y-4">
  <div className="bg-white rounded-2xl border border-[rgba(45,45,45,.08)] p-4 sm:p-5 flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><MessageCircle className="w-5 h-5 text-[#229ED9]"/><h2 className="text-lg font-bold">Telegram Integration</h2></div><p className="text-xs text-[#707070] mt-1">Outbound notifications plus secured inbound Bot API webhook.</p></div><Button variant="secondary" size="sm" onClick={load} icon={<RefreshCw className="w-3.5 h-3.5"/>}>Refresh</Button></div>
  {error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-xs text-red-700">{error}</div>}
  <div className="grid grid-cols-2 gap-3"><div className="bg-white rounded-2xl border p-4"><div className="text-[11px] text-[#777]">Bot</div><div className="text-sm font-bold mt-1">{status?.configured?'Configured':'Not configured'}</div></div><div className="bg-white rounded-2xl border p-4"><div className="text-[11px] text-[#777]">Webhook</div><div className="text-sm font-bold mt-1">{status?.webhook_configured?'Configured':'Not configured'}</div></div></div>
  <div className="bg-white rounded-2xl border p-4 sm:p-5 space-y-3"><div className="flex items-center gap-2"><Webhook className="w-4 h-4"/><h3 className="text-sm font-bold">Secure Webhook</h3></div><input value={webhookUrl} onChange={e=>setWebhookUrl(e.target.value)} placeholder="https://your-domain.com" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><div className="flex gap-2"><Button variant="primary" onClick={configure}>Configure Webhook</Button><Button variant="secondary" onClick={async()=>{try{await notificationsApi.removeWebhook();await load()}catch(e:any){setError(e?.response?.data?.detail||'Webhook removal failed.')}}}>Remove</Button></div><div className="text-[10px] text-[#777]">Server requires TELEGRAM_WEBHOOK_SECRET (minimum 16 characters). Webhook accepts only linked chats.</div></div>
  <div className="bg-white rounded-2xl border p-4 sm:p-5 space-y-3"><div className="flex items-center gap-2"><Link2 className="w-4 h-4"/><h3 className="text-sm font-bold">Link Telegram Chat to ERP User</h3></div><input value={linkChat} onChange={e=>setLinkChat(e.target.value)} placeholder="Telegram Chat ID" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><input value={linkUser} onChange={e=>setLinkUser(e.target.value)} placeholder="ERP User ID" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><input value={linkBranch} onChange={e=>setLinkBranch(e.target.value)} placeholder="Outlet/Branch ID (required for outlet Q&A)" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><Button variant="primary" onClick={link} icon={<Link2 className="w-3.5 h-3.5"/>}>Link Chat</Button>{links.map(l=><div key={l.id} className="p-3 rounded-xl bg-[#FAF8F5] border flex items-center justify-between gap-3"><div className="text-[11px] min-w-0"><b>{l.chat_id}</b> · user {l.user_id}<br/>{l.branch_id||'Head Office'} · {l.username||'no username'} · {l.is_active?'ACTIVE':'INACTIVE'}</div><button onClick={async()=>{try{await notificationsApi.unlink(l.id);await load()}catch(e:any){setError('Unlink failed.')}}} className="p-2 rounded-lg border bg-white"><Unlink className="w-3.5 h-3.5"/></button></div>)}</div>
  <div className="bg-white rounded-2xl border p-4 sm:p-5 space-y-3"><h3 className="text-sm font-bold">Send Telegram Notification</h3><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Chat ID / Group Chat ID" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title (optional)" className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message" rows={4} className="w-full px-3 py-2.5 rounded-xl bg-[#FAF8F5] border text-xs"/><Button variant="primary" onClick={send} disabled={loading||!chat.trim()||!message.trim()} icon={<Send className="w-3.5 h-3.5"/>}>{loading?'Queued…':'Queue Telegram Notification'}</Button></div>
  <div className="bg-white rounded-2xl border p-4 sm:p-5"><h3 className="text-sm font-bold mb-3">Notification History</h3><div className="space-y-2">{rows.length===0?<div className="text-xs text-[#777]">No notifications recorded.</div>:rows.map(r=><div key={r.id} className="p-3 rounded-xl bg-[#FAF8F5] border flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-xs font-bold">{r.title||r.eventType||'Telegram Notification'}</div><div className="text-[11px] text-[#555] mt-1 break-words">{r.message}</div><div className="text-[10px] text-[#888] mt-1">{r.chatId} · {r.status} · attempts {r.attempts}</div>{r.lastError&&<div className="text-[10px] text-red-600 mt-1">{r.lastError}</div>}</div>{r.status==='FAILED'&&<button onClick={async()=>{await notificationsApi.retry(r.id);await load()}} className="p-2 rounded-lg border bg-white"><RotateCcw className="w-3.5 h-3.5"/></button>}</div>)}</div></div>
 </div>
}
