'use client';
import React,{useCallback,useEffect,useState} from 'react';
import {Banknote, CreditCard, RefreshCw, ShieldCheck, Smartphone, ArrowDownToLine, ArrowUpFromLine, LockKeyhole, CheckCircle2} from 'lucide-react';
import {useOutlet} from '@/context/OutletContext';
import {cashierShiftApi, CashSession, CashMovementType} from '@/api/cashierShift';
import Button from '@/components/ui/Button';

const money=(v:number)=>`₹${Number(v||0).toFixed(2)}`;
export default function CashierShiftWorkspace(){
 const {activeOutlet}=useOutlet(); const [session,setSession]=useState<CashSession|null>(null); const [history,setHistory]=useState<CashSession[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
 const [opening,setOpening]=useState(''); const [movement,setMovement]=useState<CashMovementType>('CASH_IN'); const [amount,setAmount]=useState(''); const [reason,setReason]=useState(''); const [counted,setCounted]=useState(''); const [varianceReason,setVarianceReason]=useState(''); const [reconcileNotes,setReconcileNotes]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,h]=await Promise.all([cashierShiftApi.active(activeOutlet.id),cashierShiftApi.history(activeOutlet.id)]);setSession(a);setHistory(h);}catch(e:any){setError(e?.response?.data?.detail||'Unable to load cashier shift.')}finally{setLoading(false)}},[activeOutlet.id]);
 useEffect(()=>{load()},[load]); useEffect(()=>{if(!success)return;const t=setTimeout(()=>setSuccess(''),3000);return()=>clearTimeout(t)},[success]);
 const open=async()=>{const n=Number(opening);if(!Number.isFinite(n)||n<0){setError('Enter a valid opening float.');return}setSaving(true);setError('');try{const s=await cashierShiftApi.open({branch_id:activeOutlet.id,opening_float:n,notes:'Cashier shift opening'});setSession(s);setOpening('');setSuccess(`Shift ${s.sessionNumber} opened.`);await load()}catch(e:any){setError(e?.response?.data?.detail||'Shift could not be opened.')}finally{setSaving(false)}};
 const addMovement=async()=>{const n=Number(amount);if(!session||!Number.isFinite(n)||n<=0||!reason.trim()){setError('Enter amount and reason.');return}setSaving(true);setError('');try{const s=await cashierShiftApi.movement(session.id,{movement_type:movement,amount:n,reason:reason.trim()});setSession(s);setAmount('');setReason('');setSuccess('Cash movement recorded.');await load()}catch(e:any){setError(e?.response?.data?.detail||'Movement could not be recorded.')}finally{setSaving(false)}};
 const close=async()=>{const n=Number(counted);if(!session||!Number.isFinite(n)||n<0){setError('Enter physical counted cash.');return}setSaving(true);setError('');try{const s=await cashierShiftApi.close(session.id,{closing_cash:n,variance_reason:varianceReason.trim()||undefined,notes:'Shift closed from Cashier Control'});setSession(s);setSuccess(`Shift closed. Variance ${money(Number(s.cashVariance||0))}`);await load()}catch(e:any){setError(e?.response?.data?.detail||'Shift could not be closed.')}finally{setSaving(false)}};
 const reconcile=async()=>{if(!session||!reconcileNotes.trim()){setError('Reconciliation note is required.');return}setSaving(true);setError('');try{const s=await cashierShiftApi.reconcile(session.id,reconcileNotes.trim());setSession(s);setReconcileNotes('');setSuccess('Shift reconciled successfully.');await load()}catch(e:any){setError(e?.response?.data?.detail||'Reconciliation failed.')}finally{setSaving(false)}};
 const m=session?.liveMetrics; return <section className="space-y-4 pb-24">
  <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#8A8A8A] font-bold">Cashier Control</p><h1 className="text-2xl font-bold">Shift & Reconciliation</h1><p className="text-xs text-[#707070] mt-1">{activeOutlet.name}</p></div><Button variant="secondary" onClick={load} disabled={loading} icon={<RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>}>Refresh</Button></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-xs text-green-700 flex gap-2"><CheckCircle2 className="w-4 h-4"/>{success}</div>}
  {!session&&<div className="rounded-2xl bg-white border border-black/5 p-5"><div className="flex items-center gap-2 mb-3"><Banknote className="w-5 h-5 text-[#B8862D]"/><div><h2 className="font-bold">Open Cashier Shift</h2><p className="text-[10px] text-[#777]">Start with the physical opening float.</p></div></div><div className="grid sm:grid-cols-[1fr_auto] gap-2"><input className="field" type="number" min="0" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="Opening float ₹"/><Button variant="gold" loading={saving} onClick={open}>Open Shift</Button></div></div>}
  {session&&<>
   <div className="rounded-2xl bg-white border border-[#C79A3B]/25 p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-bold">#{session.sessionNumber}</span><span className="text-[9px] px-2 py-1 rounded-full bg-[#F1E4C5] text-[#B8862D] font-bold">{session.status}</span><span className="ml-auto text-[10px] text-[#777]">Opened {new Date(session.openedAt).toLocaleString()}</span></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">{[["Cash Sales",m?.cashSales||0,Banknote],["UPI Sales",m?.upiSales||0,Smartphone],["Card Sales",m?.cardSales||0,CreditCard],["Expected Drawer",m?.expectedDrawerCash||0,LockKeyhole]].map(([l,v,I]:any)=><div key={l} className="rounded-xl bg-[#FAF8F5] p-3"><I className="w-4 h-4 text-[#B8862D] mb-2"/><div className="font-bold">{money(v)}</div><div className="text-[9px] uppercase tracking-wider text-[#777] font-semibold">{l}</div></div>)}</div></div>
   {session.status==='OPEN'&&<div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl bg-white border border-black/5 p-4"><h2 className="font-bold text-sm mb-3">Cash Movement</h2><div className="grid sm:grid-cols-2 gap-2"><select className="field" value={movement} onChange={e=>setMovement(e.target.value as CashMovementType)}><option value="CASH_IN">Cash In</option><option value="CASH_OUT">Cash Out</option><option value="CLOSING_DROP">Safe Drop</option></select><input className="field" type="number" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount ₹"/><input className="field sm:col-span-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason *"/></div><Button className="mt-3" variant="secondary" loading={saving} onClick={addMovement} icon={<ArrowDownToLine className="w-4 h-4"/>}>Record Movement</Button></div>
   <div className="rounded-2xl bg-white border border-black/5 p-4"><h2 className="font-bold text-sm mb-3">Close Shift</h2><input className="field" type="number" min="0" value={counted} onChange={e=>setCounted(e.target.value)} placeholder="Physical counted cash ₹"/><input className="field mt-2" value={varianceReason} onChange={e=>setVarianceReason(e.target.value)} placeholder="Variance reason (if any)"/><Button className="mt-3" variant="gold" loading={saving} onClick={close} icon={<LockKeyhole className="w-4 h-4"/>}>Close Shift</Button></div></div>}
   {session.status==='CLOSED'&&<div className="rounded-2xl bg-white border border-black/5 p-4"><h2 className="font-bold text-sm">Manager Reconciliation</h2><div className="grid grid-cols-3 gap-2 mt-3 text-xs"><div className="rounded-xl bg-[#FAF8F5] p-3">Expected<br/><b>{money(Number(session.expectedCash||0))}</b></div><div className="rounded-xl bg-[#FAF8F5] p-3">Counted<br/><b>{money(Number(session.closingCash||0))}</b></div><div className="rounded-xl bg-[#FAF8F5] p-3">Variance<br/><b>{money(Number(session.cashVariance||0))}</b></div></div><textarea className="field mt-3 min-h-20" value={reconcileNotes} onChange={e=>setReconcileNotes(e.target.value)} placeholder="Manager reconciliation note *"/><Button className="mt-3" variant="success" loading={saving} onClick={reconcile} icon={<ShieldCheck className="w-4 h-4"/>}>Reconcile Shift</Button></div>}
  </>}
  <div className="rounded-2xl bg-white border border-black/5 overflow-hidden"><div className="px-4 py-3 border-b border-black/5 flex justify-between"><span className="text-xs font-bold">Shift History</span><span className="text-[10px] text-[#777]">{history.length} records</span></div>{history.length===0?<div className="p-8 text-center text-xs text-[#777]">No shift history.</div>:history.map(s=><div key={s.id} className="px-4 py-3 border-b border-black/5 last:border-0 flex items-center justify-between gap-3"><div><div className="text-xs font-bold">#{s.sessionNumber} <span className="ml-2 text-[9px] px-2 py-0.5 rounded-full bg-[#F5F3EE]">{s.status}</span></div><div className="text-[10px] text-[#777] mt-1">{new Date(s.openedAt).toLocaleString()} · Cash sales {money(s.totalCashSales)}</div></div><div className="text-right"><div className="text-xs font-bold">Variance {s.cashVariance==null?'—':money(s.cashVariance)}</div><div className="text-[9px] text-[#777]">{s.liveMetrics.ordersCount} order(s)</div></div></div>)}</div>
 </section>
}
