'use client';
import React,{useEffect,useState} from 'react';
import { useOutlet } from '@/context/OutletContext';
import { maintenanceApi } from '@/api/maintenance';
import { MaintenanceAsset, MaintenanceTicket, MaintenanceSummary } from '@/types/maintenance.types';
import { Wrench, Plus, RefreshCw, AlertTriangle, ShieldCheck, Clock, CircleDollarSign, Search, CheckCircle2 } from 'lucide-react';
import { Badge, Button, StatCard, AlertBanner } from '@/components/ui';

const input='w-full rounded-xl border border-black/10 bg-white px-3 py-2.5 text-xs outline-none focus:border-[#C79A3B]';
const openStatuses=['OPEN','IN_PROGRESS','WAITING_PARTS'];
export default function MaintenanceWorkspace(){
 const {activeOutlet}=useOutlet(); const [tab,setTab]=useState<'tickets'|'assets'>('tickets'); const [summary,setSummary]=useState<MaintenanceSummary|null>(null); const [tickets,setTickets]=useState<MaintenanceTicket[]>([]); const [assets,setAssets]=useState<MaintenanceAsset[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showTicket,setShowTicket]=useState(false); const [showAsset,setShowAsset]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const [s,t,a]=await Promise.all([maintenanceApi.summary(activeOutlet.id),maintenanceApi.tickets({branch_id:activeOutlet.id,search:q||undefined}),maintenanceApi.assets({branch_id:activeOutlet.id})]);setSummary(s);setTickets(t);setAssets(a)}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Unable to load maintenance data')}finally{setLoading(false)}};
 useEffect(()=>{load()},[activeOutlet.id]);
 const update=async(id:string,status:string)=>{try{await maintenanceApi.updateTicket(id,{status});await load()}catch(e:any){setError(e?.response?.data?.detail||e?.message||'Update failed')}};
 return <div className="space-y-4"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#B8862D]">Maintenance & Assets</p><h1 className="text-2xl font-bold mt-1 flex items-center gap-2"><Wrench className="w-6 h-6 text-[#B8862D]"/>Maintenance Center</h1><p className="text-xs text-[#707070] mt-1">Asset register, repair tickets, downtime, cost and warranty control.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={load} loading={loading}><RefreshCw className="w-3.5 h-3.5 mr-1"/>Sync</Button><Button size="sm" onClick={()=>setShowAsset(true)}><Plus className="w-3.5 h-3.5 mr-1"/>Asset</Button><Button variant="danger" size="sm" onClick={()=>setShowTicket(true)}><Plus className="w-3.5 h-3.5 mr-1"/>Ticket</Button></div></div>
 <AlertBanner feedback={error?{type:'error',message:error}:null} onClose={()=>setError('')}/>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><StatCard title="Open Tickets" value={summary?.open_tickets??0} icon={<Clock className="w-4 h-4"/>}/><StatCard title="Critical" value={summary?.critical_tickets??0} icon={<AlertTriangle className="w-4 h-4"/>}/><StatCard title="Overdue" value={summary?.overdue_tickets??0} icon={<AlertTriangle className="w-4 h-4"/>}/><StatCard title="30d Cost" value={`₹${Number(summary?.actual_cost_30d||0).toFixed(0)}`} icon={<CircleDollarSign className="w-4 h-4"/>}/></div>
 <div className="flex gap-2"><button className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='tickets'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border border-black/10'}`} onClick={()=>setTab('tickets')}>Repair Tickets</button><button className={`px-4 py-2 rounded-xl text-xs font-bold ${tab==='assets'?'bg-[#F1E4C5] text-[#B8862D]':'bg-white border border-black/10'}`} onClick={()=>setTab('assets')}>Asset Register ({summary?.assets??0})</button><div className="ml-auto relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-[#999]"/><input className={input+' pl-9 w-56'} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search..."/></div></div>
 {tab==='tickets'?<Tickets tickets={tickets} loading={loading} update={update}/>:<Assets assets={assets} loading={loading}/>} {showTicket&&<TicketForm assets={assets} branchId={activeOutlet.id} onClose={()=>setShowTicket(false)} onCreated={()=>{setShowTicket(false);load()}}/>}{showAsset&&<AssetForm branchId={activeOutlet.id} onClose={()=>setShowAsset(false)} onCreated={()=>{setShowAsset(false);load()}}/>}</div>
}
function Tickets({tickets,loading,update}:any){return <div className="space-y-2">{loading?<p className="text-xs text-[#777]">Loading tickets...</p>:tickets.length===0?<div className="p-8 bg-white rounded-2xl border text-center text-xs text-[#777]">No maintenance tickets.</div>:tickets.map((t:MaintenanceTicket)=><div key={t.id} className="p-4 bg-white rounded-2xl border border-black/5 shadow-sm"><div className="flex justify-between gap-3"><div><b className="text-sm">{t.ticket_number} · {t.title}</b><p className="text-[10px] text-[#777] mt-1">{t.asset_name||'Unassigned asset'} {t.asset_code?`· ${t.asset_code}`:''} · {t.category}</p></div><Badge variant={t.priority==='CRITICAL'?'danger':t.status==='COMPLETED'?'success':t.status==='IN_PROGRESS'?'warning':'neutral'}>{t.priority} · {t.status}</Badge></div><p className="text-xs mt-2 text-[#505050]">{t.description}</p><div className="flex flex-wrap items-center gap-2 mt-3 text-[10px] text-[#777]"><span>Est ₹{Number(t.estimated_cost||0).toFixed(0)}</span><span>Actual ₹{Number(t.actual_cost||0).toFixed(0)}</span><span>Downtime {t.downtime_minutes||0} min</span>{t.due_at&&<span>Due {new Date(t.due_at).toLocaleDateString()}</span>}</div><div className="flex gap-1.5 mt-3">{openStatuses.includes(t.status)&&<><Button size="sm" variant="secondary" onClick={()=>update(t.id,t.status==='OPEN'?'IN_PROGRESS':'COMPLETED')}>{t.status==='OPEN'?'Start':'Complete'}</Button>{t.status!=='WAITING_PARTS'&&<Button size="sm" variant="secondary" onClick={()=>update(t.id,'WAITING_PARTS')}>Waiting Parts</Button>}</>} {t.status==='COMPLETED'&&<span className="text-[10px] text-green-700 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/>Closed</span>}</div></div>)}</div>}
function Assets({assets,loading}:any){return <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{loading?<p className="text-xs">Loading assets...</p>:assets.map((a:MaintenanceAsset)=><div key={a.id} className="p-4 bg-white rounded-2xl border border-black/5"><div className="flex justify-between"><b className="text-sm">{a.name}</b><Badge variant={a.status==='ACTIVE'?'success':'warning'}>{a.status}</Badge></div><p className="text-[10px] text-[#777] mt-1">{a.asset_code} · {a.category} {a.location?`· ${a.location}`:''}</p><div className="grid grid-cols-2 gap-2 mt-3 text-[10px]"><span>Open tickets <b>{a.open_ticket_count}</b></span><span>Warranty <b>{a.warranty_days_remaining==null?'—':a.warranty_days_remaining<0?'Expired':`${a.warranty_days_remaining}d`}</b></span></div>{a.warranty_days_remaining!=null&&a.warranty_days_remaining<=30&&a.warranty_days_remaining>=0&&<div className="mt-3 p-2 rounded-lg bg-amber-50 text-amber-800 text-[10px] flex gap-1"><ShieldCheck className="w-3 h-3"/>Warranty expires soon</div>}</div>)}</div>}
function AssetForm({branchId,onClose,onCreated}:any){const [f,setF]=useState<any>({branch_id:branchId,asset_code:'',name:'',category:'Equipment',location:'',manufacturer:'',serial_number:'',purchase_cost:0});const [busy,setBusy]=useState(false);const save=async()=>{if(!f.asset_code||!f.name||!f.category)return;setBusy(true);try{await maintenanceApi.createAsset(f);onCreated()}catch(e:any){alert(e?.response?.data?.detail||e?.message||'Could not create asset')}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-5 w-full max-w-lg space-y-3"><h3 className="font-bold">Register Asset</h3><div className="grid sm:grid-cols-2 gap-2">{[['asset_code','Asset Code'],['name','Asset Name'],['category','Category'],['location','Location'],['manufacturer','Manufacturer'],['serial_number','Serial Number']].map(([k,l])=><input key={k} className={input} placeholder={l} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<input className={input} type="number" placeholder="Purchase Cost" value={f.purchase_cost} onChange={e=>setF({...f,purchase_cost:Number(e.target.value)})}/><input className={input} type="date" placeholder="Warranty" onChange={e=>setF({...f,warranty_expiry:e.target.value?`${e.target.value}T00:00:00`:undefined})}/></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={save} loading={busy}>Save Asset</Button></div></div></div>}
function TicketForm({branchId,assets,onClose,onCreated}:any){const [f,setF]=useState<any>({branch_id:branchId,title:'',description:'',category:'General',priority:'MEDIUM',estimated_cost:0});const [busy,setBusy]=useState(false);const save=async()=>{if(!f.title||!f.description)return;setBusy(true);try{await maintenanceApi.createTicket(f);onCreated()}catch(e:any){alert(e?.response?.data?.detail||e?.message||'Could not create ticket')}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-5 w-full max-w-lg space-y-3"><h3 className="font-bold">Create Maintenance Ticket</h3><select className={input} value={f.asset_id||''} onChange={e=>setF({...f,asset_id:e.target.value||undefined})}><option value="">Select Asset (optional)</option>{assets.map((a:MaintenanceAsset)=><option key={a.id} value={a.id}>{a.asset_code} · {a.name}</option>)}</select><input className={input} placeholder="Issue title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><textarea className={input+' min-h-24'} placeholder="Describe the problem" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className={input} placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><select className={input} value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><input className={input} type="number" placeholder="Estimated Cost" value={f.estimated_cost} onChange={e=>setF({...f,estimated_cost:Number(e.target.value)})}/><input className={input} type="date" onChange={e=>setF({...f,due_at:e.target.value?`${e.target.value}T23:59:59`:undefined})}/></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={save} loading={busy}>Create Ticket</Button></div></div></div>}
