'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { Bell, CalendarClock, CheckCircle2, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import { apiClient } from '@/api/client';
import { Button, Badge, StatCard } from '@/components/ui';
import { useOutlet } from '@/context/OutletContext';

const REPORT_TYPES = ['EXECUTIVE_SUMMARY','SALES_SUMMARY','INVENTORY_VALUATION','FOOD_COST_VARIANCE','WASTAGE_SUMMARY','PROCUREMENT_SUMMARY'];
const FREQS = ['DAILY','WEEKLY','BI_WEEKLY','MONTHLY'];
export default function ScheduledReportsAlertsWorkspace() {
  const { activeOutlet } = useOutlet();
  const [schedules,setSchedules]=useState<any[]>([]); const [alerts,setAlerts]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState('');
  const [reportType,setReportType]=useState(REPORT_TYPES[0]); const [frequency,setFrequency]=useState('DAILY'); const [recipients,setRecipients]=useState('');
  const load=useCallback(async()=>{setLoading(true);setMsg('');try{const [s,a]=await Promise.all([apiClient.get('/reports/schedules',{params:{branch_id:activeOutlet.id}}),apiClient.get('/reports/alerts',{params:{branch_id:activeOutlet.id}})]);setSchedules(s.data||[]);setAlerts(a.data?.alerts||[]);}catch(e:any){setMsg(e?.response?.data?.detail||'Unable to load scheduled reports and alerts.');}finally{setLoading(false);}},[activeOutlet.id]);
  useEffect(()=>{load();},[load]);
  const create=async()=>{setMsg('');try{await apiClient.post('/reports/schedules',{report_type:reportType,frequency,branch_id:activeOutlet.id,recipients:recipients.split(',').map(x=>x.trim()).filter(Boolean)});setMsg('Schedule created.');setRecipients('');await load();}catch(e:any){setMsg(e?.response?.data?.detail||'Schedule creation failed.');}};
  const runDue=async()=>{try{const r=await apiClient.post('/reports/schedules/run-due');setMsg(`${r.data?.processed||0} due schedule(s) processed.`);await load();}catch(e:any){setMsg(e?.response?.data?.detail||'Scheduled run failed.');}};
  const toggle=async(id:string,active:boolean)=>{try{await apiClient.patch(`/reports/schedules/${id}`,null,{params:{is_active:!active}});await load();}catch(e:any){setMsg('Schedule update failed.');}};
  return <div className="space-y-5">
    <div className="rounded-2xl bg-white border border-[rgba(45,45,45,0.08)] p-5 shadow-sm"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarClock className="w-5 h-5 text-[#C79A3B]"/><h2 className="text-xl font-bold">Scheduled Reports & Alerts</h2><Badge variant="outlet">[{activeOutlet.code}]</Badge></div><p className="text-xs text-[#707070] mt-1">Live scheduled-report control and operational alerts. Delivery credentials are not invented or stored here.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={load} loading={loading} icon={<RefreshCw className="w-3.5 h-3.5"/>}>Refresh</Button><Button variant="primary" size="sm" onClick={runDue} icon={<Play className="w-3.5 h-3.5"/>}>Run Due</Button></div></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><StatCard title="Active Schedules" value={String(schedules.filter(x=>x.is_active).length)} subtitle="Configured" icon={<CalendarClock className="w-4 h-4"/>}/><StatCard title="Alerts" value={String(alerts.length)} subtitle="Live" icon={<Bell className="w-4 h-4"/>}/><StatCard title="Critical" value={String(alerts.filter(x=>x.severity==='CRITICAL').length)} subtitle="Immediate" icon={<ShieldAlert className="w-4 h-4"/>}/><StatCard title="Outlet" value={activeOutlet.code} subtitle="Scope" icon={<CheckCircle2 className="w-4 h-4"/>}/></div>
    {msg&&<div className="rounded-xl border border-[#C79A3B]/30 bg-[#FAF8F5] px-4 py-3 text-xs font-medium">{msg}</div>}
    <div className="rounded-2xl bg-white border p-5 shadow-sm"><h3 className="font-bold mb-3">Create Schedule</h3><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><select className="border rounded-xl px-3 py-3 text-sm" value={reportType} onChange={e=>setReportType(e.target.value)}>{REPORT_TYPES.map(x=><option key={x}>{x}</option>)}</select><select className="border rounded-xl px-3 py-3 text-sm" value={frequency} onChange={e=>setFrequency(e.target.value)}>{FREQS.map(x=><option key={x}>{x}</option>)}</select><input className="border rounded-xl px-3 py-3 text-sm" value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="Recipients, comma separated"/><Button variant="primary" onClick={create}>Create</Button></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-2xl bg-white border p-5 shadow-sm"><h3 className="font-bold mb-3">Live Alerts</h3>{alerts.length===0?<div className="text-sm text-[#707070] py-8 text-center">No active alerts.</div>:<div className="space-y-2">{alerts.map((a,i)=><div key={i} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b className="text-sm">{a.title}</b><span className="text-[10px] font-bold">{a.severity}</span></div><p className="text-xs text-[#707070] mt-1">{a.message}</p></div>)}</div>}</div>
    <div className="rounded-2xl bg-white border p-5 shadow-sm"><h3 className="font-bold mb-3">Schedules</h3>{schedules.length===0?<div className="text-sm text-[#707070] py-8 text-center">No schedules configured.</div>:<div className="space-y-2">{schedules.map(s=><div key={s.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{s.report_type}</b><div className="text-xs text-[#707070] mt-1">{s.frequency} · Next: {s.next_run_at?new Date(s.next_run_at).toLocaleString():'—'}</div></div><button onClick={()=>toggle(s.id,s.is_active)} className="text-xs font-bold underline">{s.is_active?'Disable':'Enable'}</button></div></div>)}</div>}</div></div>
  </div>;
}
